# Generated by Django 5.1.3 on 2024-11-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Join', '0003_alter_task_subtasksprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(),
        ),
    ]
