# Generated by Django 5.1.3 on 2024-11-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Join', '0004_subtask_alter_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='contacts',
        ),
        migrations.AddField(
            model_name='task',
            name='contacts',
            field=models.ManyToManyField(to='Join.contact'),
        ),
    ]
