# Generated by Django 5.1.3 on 2024-12-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Join', '0006_alter_task_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='contacts',
            field=models.ManyToManyField(to='Join.contact'),
        ),
    ]
