# Generated by Django 5.1.3 on 2024-12-20 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Join', '0007_alter_task_contacts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='contacts',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
